# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c20eedb7c7582459338c6abf5f9548680b8c900b1532c76ad4973f9c6631ae9e908cc85879a4a7e25eced9917befdd2fcdd383dcc0612fcdb716e1374ca66f45

test:
  secret_key_base: 6bdc61a7da0d5e08353184efcd06b3cabfd9e6bbe431cc22520fb8430f54c9ffa73560dc519f44fbf491370e0a0fd5328a23c5ecf6a06e36c3b87f5e5391edeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
